[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.9.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/ethereum/go-ethereum"
  unused-packages = false

[[prune.project]]
  name = "github.com/karalabe/usb"
  unused-packages = false

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

 [[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"
