[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.26"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[prune]
  go-tests = true
  unused-packages = true

# Bug on dep that remove of C files even without setting prune non-go
# Tempory fix is to enable unused-package for dep project with C-files directory.
# https://github.com/golang/dep/issues/1725
# https://github.com/golang/dep/issues/1306

[[prune.project]]
  name = "github.com/ethereum/go-ethereum"
  unused-packages = false

[[prune.project]]
  name = "github.com/karalabe/hid"
  unused-packages = false

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

 [[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

 [[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"